### ISSUE TITLE
docker版本暗黑模式显示为明亮；两边侧边栏下面多出不明空白块

### ISSUE THREAD

**Issue by iowong** [svchord/Rem-Craft#117]
思源笔记版本号：2.7.6

本地 Rem Craft 版本号：2.6.0

确认关闭其他代码片段后是否能重现问题：是

问题描述：docker版本暗黑模式显示为明亮；两边侧边栏下面多出不明空白块

复现步骤：

操作系统：CentOS 7.6.1810 x86_64
![微信截图_20230223124420](https://user-images.githubusercontent.com/74191259/220823317-55e9ba44-cf69-47e8-aca9-45db47b460df.png)
---
其他主题均不存在此问题
![微信截图_20230223124526](https://user-images.githubusercontent.com/74191259/220823337-3bc4d71f-2b1c-4613-ace9-0bc4660f1981.png)

**Comment by h2o2o** [comment]
我发现是下面的代码覆盖了思源默认的`fn__none`属性导致不能收起书签栏
```scss
// 隐藏的边窗
&.fn__none {
    display: flex  !important;
}
```
可以通过替换 `themes/Rem Craft/theme.css` 中的 `flex`  为 `none`来实现切换
```css
// 查找文本
#layouts>.fn__flex>.fn__flex-column:not(.layout__center)>.fn__flex.fn__none{display:flex !important}

// 替换为下面的内容
#layouts>.fn__flex>.fn__flex-column:not(.layout__center)>.fn__flex.fn__none{display:none !important}
```

**不清楚上述替换后是否会出现其他的Bug**
