### ISSUE TITLE
不同级别的标题区分度较低

### ISSUE THREAD

**Issue by sun-weihan** [svchord/Rem-Craft#134]
不同级别标题仅仅是字号大小不一样，很难一眼区分开。
建议自动添加`1.1.1`、`1.1.2`等等此类的序号（类似Dark+主题），或者添加标记标识标题级别（类似Savor主题）

**Comment by SsparKluo** [comment]
这个可以自己用代码片段解决，我个人感觉现在这样其实也没什么问题。

这是我之前从社区复制的一段
```css
body {
    counter-reset: h1-count 0;
}

.h1 {
    counter-reset: h2-count 0;
}

.h2 {
    counter-reset: h3-count 0;
}

.h3 {
    counter-reset: h4-count 0;
}

.h4 {
    counter-reset: h5-count 0;
}

.h5 {
    counter-reset: h6-count 0;
}

.protyle-wysiwyg [data-node-id].h1:before,
.b3-typography h1:before {
    display: block;
    float: left;
    font-size: 100%;
    counter-increment: h1-count;
    content: counter(h1-count) ".\00A0";
}

.protyle-wysiwyg [data-node-id].h2:before,
.b3-typography h2:before {
    display: block;
    float: left;
    font-size: 100%;
    counter-increment: h2-count;
    content: counter(h1-count) "."counter(h2-count) ".\00A0";
}

.protyle-wysiwyg [data-node-id].h3:before,
.b3-typography h3:before {
    display: block;
    float: left;
    font-size: 100%;
    counter-increment: h3-count;
    content: counter(h1-count) "."counter(h2-count) "."counter(h3-count) ".\00A0";
}

.protyle-wysiwyg [data-node-id].h4:before,
.b3-typography h4:before {
    display: block;
    float: left;
    font-size: 100%;
    counter-increment: h4-count;
    content: counter(h1-count) "."counter(h2-count) "."counter(h3-count) "."counter(h4-count) ".\00A0";
}

.protyle-wysiwyg [data-node-id].h5:before,
.b3-typography h5:before {
    display: block;
    float: left;
    font-size: 100%;
    counter-increment: h5-count;
    content: counter(h1-count) "."counter(h2-count) "."counter(h3-count) "."counter(h4-count) "."counter(h5-count) ".\00A0";
}

.protyle-wysiwyg [data-node-id].h6:before,
.b3-typography h6:before {
    display: block;
    float: left;
    font-size: 100%;
    counter-increment: h6-count;
    content: counter(h1-count) "."counter(h2-count) "."counter(h3-count) "."counter(h4-count) "."counter(h5-count) "."counter(h6-count) ".\00A0";
}
```
