### ISSUE TITLE
临时修复 v2.6.12 在思源 2.10.10 样式的代码片段

### ISSUE THREAD

**Issue by mohuishou** [svchord/Rem-Craft#139]
思源笔记版本号：
 2.10.10
本地 Rem Craft 版本号：
v2.6.12 

- fix:  `/` 面板不分栏的问题 #135 
- fix: 折叠块符号错位的问题
- fix: 操作图标和列表块小点没对齐的问题
- fix: 代码块显示异常 #136 

```css
.protyle-wysiwyg [data-node-id].li > .protyle-action:after{
  margin: -1px 0px 0px -1px !important;
}

.protyle-gutters button {
  padding: 0px 10px !important;
}

.protyle-hint.hint--menu > div {
    columns: 170px 4;
    column-gap: 12px;
    column-rule: 1px solid rgba(var(--border-3));
    max-height: none !important;
    width: auto !important;
    min-width: 730px;
}

.protyle-hint.hint--menu .b3-menu__separator {
    border-bottom: none;

}

.b3-typography .hljs.protyle-linenumber, .protyle-wysiwyg .hljs.protyle-linenumber {
  margin-left: 0px;
}

.b3-typography .protyle-linenumber__rows, .protyle-wysiwyg .protyle-linenumber__rows{
  width: 3.6em;
}
```
