### ISSUE TITLE
建议取消掉 未知超链接前的标志（siyuan://开头的）

### ISSUE THREAD

**Issue by langyamu** [svchord/Rem-Craft#31]
我这边是用了一段时间以后笔记里大部分链接都是 思源的笔记链接 也就导致很多链接前都是 未知的标志 感觉有点多余，影响观看

### 改以后
![image](https://user-images.githubusercontent.com/40269393/184901808-ea34a820-6dee-4584-b324-58380a1d9a85.png)
### 改之前
![image](https://user-images.githubusercontent.com/40269393/184901989-01757f92-0619-496c-89e0-0947e87fc4fc.png)

是不是感觉清爽了不少

styles\pages\editor\_block-link.scss:81行

```SCSS
.protyle-wysiwyg [data-node-id] span[data-type='a'][data-href^="siyuan://"]:not(:empty)::before,
.protyle-wysiwyg [data-node-id] a[href^="siyuan://"]::before,
.b3-typography a[href^="siyuan://"]::before
{
  display: none;
}
```
