### ISSUE TITLE
感觉可以把编辑器的 固定 padding 去掉了

### ISSUE THREAD

**Issue by langyamu** [svchord/Rem-Craft#33]
官方给的 `设置 - 编辑器 - 自适应宽度` 功能已经实现了
![动画 (3)](https://user-images.githubusercontent.com/40269393/188619229-f4b64f4d-4c46-416a-b786-1ccf524bb572.gif)
另外下边是我对主题的一点改造，，，
* Rem Craft 主题改造

  * `styles\protyle\block\list.scss`

    * 大纲辅助线颜色 —— 鼠标移入块高亮

      ```scss
      $list-border-color: #4078f2;
      .protyle-wysiwyg {
        [data-node-id].li {
         &:hover > [data-node-id]:before {
            border-left: 1px solid $list-border-color !important;
            transition: var(--b3-transition);
            opacity: 0.86;
          }
        }
      }
      ```
