### ISSUE TITLE
请问CSS哪里可以改高亮的颜色，以前是蓝色现在是这个棕色好丑啊

### ISSUE THREAD

**Issue by EZ4BRUCE** [svchord/Rem-Craft#36]

**Comment by svchord** [comment]
我才发现这是个暗黑模式下的bug…待会就改，不过刚发了版，要等下个版本了

**Comment by svchord** [comment]
如果你比较急用的话，可以在`theme.css`的末尾添加如下代码：

```css
.b3-typography mark,
.protyle-wysiwyg mark {
    background-color: transparent;
}
```
