### ISSUE TITLE
段间距

### ISSUE THREAD

**Issue by itachaaa** [svchord/Rem-Craft#47]
段间距感觉太大了，有点难受，不知道是否可以调整？感谢

**Comment by svchord** [comment]
目前的段间距和行高是参考语雀的，按理说应该不会太大啊

**Comment by itachaaa** [comment]
![image](https://user-images.githubusercontent.com/31896600/198461577-99d6f0bb-830a-4a1b-b45c-def35996d26f.png)
![image](https://user-images.githubusercontent.com/31896600/198461857-1a82a282-c363-4503-af55-a08aec050f4c.png)

以上是两个对比，不晓得问题出在哪里，加上思源是普通换行就会起一个新的段落，导致两行文字差距很大，可以参考下图二 light-blue 的效果看是不是有点大呢，当然也可能是我不太习惯哈。

**Comment by svchord** [comment]
新版有了代码片段功能，你可以在`设置`-`外观`-`代码片段`里添加如下css：

```css
.b3-typography > p,
.protyle-wysiwyg > .p {
  margin: 18px 0;
}
```

其中`18px`是主题默认段间距，你可以自行调整
