### ISSUE TITLE
能否调大标题的字号？

### ISSUE THREAD

**Issue by heimi98** [svchord/Rem-Craft#61]
能否调大标题的字号？H4 标题的字号甚至比正文字号都小。

**Comment by svchord** [comment]
标题的字号大小是参考语雀的，你可以使用代码片段功能添加如下css：

```css
.b3-typography h4,
.protyle-wysiwyg .h4{
  font-size: 16px;
}
```

其中`16px`是主题默认H4字号大小，你可以自己修改
