### ISSUE TITLE
支持滚动到页面顶部与底部

### ISSUE THREAD

**Issue by OriOYue** [svchord/Rem-Craft#73]
### 但是Rem craf主题好像将这个隐藏了，作者大大能加进来吗？感谢！

**Comment by svchord** [comment]
可以用代码片段先顶顶

```css
.protyle-scroll {
    right: 20px;
}
```
