### ISSUE TITLE
[问题]在ctrl+r的查找与替换菜单中的"全部替换""替换"没了

### ISSUE THREAD

**Issue by a15355447898a** [svchord/Rem-Craft#76]
这是正常情况
![](https://gchat.qpic.cn/gchatpic_new/86254368/538155062-2965582952-46A0F4E66B760F8B463113B509EE60E7/0?term=255&is_origin=0)
这是使用这个主题后
![](https://gchat.qpic.cn/gchatpic_new/3293194779/538155062-2264498180-3650968A6273117A170E433F8835F417/0?term=255&is_origin=0)

**Comment by svchord** [comment]
收到，已定位到问题，下个版本更新，你可以先用下面的代码片段顶顶：

```css
#replaceInput{
    flex-shrink: unset;
}
```
