### ISSUE TITLE
更新最新版主题后右上角的关闭按钮（×）失效了

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#85]
这个关闭按钮点击没有任何反应！
![image](https://user-images.githubusercontent.com/116488969/206168139-e212dfcc-3e4c-436f-87be-ca21d87bb732.png)

**Comment by svchord** [comment]
下个版本修复，先用代码片段顶顶：

```css
#dockRight{
-webkit-app-region: no-drag;
}

```
